name: deploy Website for Session4
on: [push]
jobs:
  build:
    
    runs-on: ubuntu-latest
    name: Deploying to surge
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
         node-version: 12
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@2.0.2
        with:
          #yarn Command
          cmd: Install #npm install / yarn install
      - name: Creating build
        run: yarn build
      - name: Installaiton surge
        run: npm Install -g surge
      - name: Run surge / deploying on surge
        run: surge ./build session4-haroon.surge.sh --token ${{secrets.SESSION4_TOKEN}}
